---
roles:
  - name: stackhpc.os-openstackclient
    src: https://github.com/scriptkiddy/ansible-role-os-openstackclient.git
    version: macos_compatibility
  - name: stackhpc.os-images
    src: https://github.com/stackhpc/ansible-role-os-images.git

collections:
  - name: openstack.cloud
    version: 1.2.1
    type: galaxy
