---
galaxy_info:
  role_name: os_openstacksdk
  author: Mark Goddard
  description: >
    Role to install the python package openstacksdk
  company: StackHPC Ltd
  license: Apache2
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - Sierra
        - High-Sierra
        - Big-Sur
  galaxy_tags:
    - cloud
    - openstack
    - python
    - openstacksdk

dependencies: []
