name: Build Images

on:
  workflow_dispatch:

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - run: python --version

      - run: pip install -r requirements.txt

      - run: ansible-galaxy install -p ansible/roles -r requirements.yml

      - run: ansible-playbook --version

      - name: Build images
        run: ./tools/nesi_akl1-images.sh --images
